export const APPLICATION_CREATE = 'APPLICATION_CREATE';
export const APPLICATION_EDIT = 'APPLICATION_EDIT';
export const APPLICATION_DELETE = 'APPLICATION_DELETE';
export const APPLICATION_READ = 'APPLICATION_READ';

export const PAYMENT_PLAN_CREATE = 'PAYMENT_PLAN_CREATE';
export const PAYMENT_PLAN_READ = 'PAYMENT_PLAN_READ';
export const PAYMENT_PLAN_DELETE = 'PAYMENT_PLAN_DELETE';
export const PAYMENT_PLAN_EDIT = 'PAYMENT_PLAN_EDIT';

export const USER_CREATE = 'USER_CREATE';

export const ROLE_CREATE = 'ROLE_CREATE';
export const ROLE_READ = 'ROLE_READ';
export const ROLE_DELETE = 'ROLE_DELETE';
export const ROLE_EDIT = 'ROLE_EDIT';
